### ISSUE TITLE
Various user-facing spelling errors

### ISSUE THREAD

**Issue by j-tan** [ausaccessfed/shibboleth-idp-2-deployer#149]
Minor spelling errors presented through the user interface.

**Comment by trsau** [comment]
Thanks Jason, please correct them as you find them. I hope to have all the
wording reviewed before release.

Thanks Terry

On Wednesday, 18 February 2015, j-tan <notifications@github.com> wrote:

> Minor spelling errors presented through the user interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ausaccessfed/shibboleth-idp-2-deployer/issues/149>.
>


-- 
*Terry Smith* | Technical Manager / Boost Program Manager | *Australian
Access Federation Inc*
*Tel:*  +61 7 3138 2424 | *Mob:*  0414 692 424
*Email* t.smith@aaf.edu.au <http://twitter.com/ausaccessfed> | *Web:*
http://www.aaf.edu.au <http://twitter.com/ausaccessfed> *| Support: *
http://support.aaf.edu.au
*Twitter:* http://twitter.com/ausaccessfed *Facebook: *
http://facebook.com/ausaccessfed
*Mail: **PO Box 2104 | kelvin Grove  QLD  4059 | Australia*
