### ISSUE TITLE
uApprove download link appears to have changed

### ISSUE THREAD

**Issue by j-tan** [ausaccessfed/shibboleth-idp-2-deployer#167]
The link to download uApprove has appeared to have changed to something similar to below:
```
https://forge.switch.ch/redmine/attachments/download/<randomly generated number>/uApprove-<version-number>.zip
```
How should I account for this?

**Comment by trsau** [comment]
The number looks like some sort of sequence number and I don't expect to change once assigned to a particular file. Use the URL with the number embedded.
